spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hyperlightlogistics
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #none #update #validate
    properties:
      hibernate:
        format_sql: true #?
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
#      Uncomment the lines below if needed
#      enable-auto-commit: false
#      max-poll-records: 5
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

server:
  port: 8080

grpc:
  server:
    host: localhost
    port: 50051